; ******************************************************************************
; mega drive memory map
;
; ******************************************************************************


RAM_SIZE:  equ 0xFFFF
RAM_START: equ 0x0000
RAM_END:   equ RAM_START + RAM_SIZE
RAM_ADDR:  equ 0x00FF0000

STACK_SIZE:  equ 0x00FE
STACK_START: equ RAM_END - 1
STACK_END:   equ STACK_START - STACK_SIZE
STACK_ADDR:  equ RAM_ADDR + STACK_START

; --------------------------------------
; text utils
; --------------------------------------

RAM_BYTE_DEC_FLIP_STR:      equ RAM_ADDR + RAM_START
RAM_BYTE_DEC_FLIP_STR_SIZE: equ 0x4

; --------------------------------------
; uptime
; --------------------------------------

RAM_UPTIME_VINT:            equ RAM_BYTE_DEC_FLIP_STR + RAM_BYTE_DEC_FLIP_STR_SIZE
RAM_UPTIME_VINT_SIZE:       equ 0x2

RAM_UPTIME_VINT_TOTAL:      equ RAM_UPTIME_VINT + RAM_UPTIME_VINT_SIZE
RAM_UPTIME_VINT_TOTAL_SIZE: equ 0x4

RAM_UPTIME_SEC:             equ RAM_UPTIME_VINT_TOTAL + RAM_UPTIME_VINT_TOTAL_SIZE
RAM_UPTIME_SEC_SIZE:        equ 0x2
RAM_UPTIME_SEC_STR:         equ RAM_UPTIME_SEC + RAM_UPTIME_SEC_SIZE
RAM_UPTIME_SEC_STR_SIZE:    equ 0x4

RAM_UPTIME_MIN:             equ RAM_UPTIME_SEC_STR + RAM_UPTIME_SEC_STR_SIZE
RAM_UPTIME_MIN_SIZE:        equ 0x2
RAM_UPTIME_MIN_STR:         equ RAM_UPTIME_MIN + RAM_UPTIME_MIN_SIZE
RAM_UPTIME_MIN_STR_SIZE:    equ 0x4

RAM_UPTIME_HOUR:            equ RAM_UPTIME_MIN_STR + RAM_UPTIME_MIN_STR_SIZE
RAM_UPTIME_HOUR_SIZE:       equ 0x2
RAM_UPTIME_HOUR_STR:        equ RAM_UPTIME_HOUR + RAM_UPTIME_HOUR_SIZE
RAM_UPTIME_HOUR_STR_SIZE:   equ 0x4

; --------------------------------------
; system
; --------------------------------------

RAM_MD_VER:      equ RAM_UPTIME_HOUR_STR + RAM_UPTIME_HOUR_STR_SIZE
RAM_MD_VER_SIZE: equ 0x2

RAM_M68K_SR:          equ RAM_MD_VER + RAM_MD_VER_SIZE
RAM_M68K_SR_SIZE:     equ 0x4
RAM_M68K_SR_STR:      equ RAM_M68K_SR + RAM_M68K_SR_SIZE
RAM_M68K_SR_STR_SIZE: equ 0xA

RAM_M68K_PC:          equ RAM_M68K_SR_STR + RAM_M68K_SR_STR_SIZE
RAM_M68K_PC_SIZE:     equ 0x4
RAM_M68K_PC_STR:      equ RAM_M68K_PC + RAM_M68K_PC_SIZE
RAM_M68K_PC_STR_SIZE: equ 0xA

RAM_M68K_D0_D7_A0_A7:      equ RAM_M68K_PC_STR + RAM_M68K_PC_STR_SIZE
RAM_M68K_D0_D7_A0_A7_SIZE: equ 0x40 ; 16 registers [d0-d7/ a0-a7] / 4 bytes each

RAM_M68K_D0_STR:      equ RAM_M68K_D0_D7_A0_A7 + RAM_M68K_D0_D7_A0_A7_SIZE
RAM_M68K_D0_STR_SIZE: equ 0xA

RAM_M68K_D1_STR:      equ RAM_M68K_D0_STR + RAM_M68K_D0_STR_SIZE
RAM_M68K_D1_STR_SIZE: equ 0xA

RAM_M68K_D2_STR:      equ RAM_M68K_D1_STR + RAM_M68K_D1_STR_SIZE
RAM_M68K_D2_STR_SIZE: equ 0xA

RAM_M68K_D3_STR:      equ RAM_M68K_D2_STR + RAM_M68K_D2_STR_SIZE
RAM_M68K_D3_STR_SIZE: equ 0xA

RAM_M68K_D4_STR:      equ RAM_M68K_D3_STR + RAM_M68K_D3_STR_SIZE
RAM_M68K_D4_STR_SIZE: equ 0xA

RAM_M68K_D5_STR:      equ RAM_M68K_D4_STR + RAM_M68K_D4_STR_SIZE
RAM_M68K_D5_STR_SIZE: equ 0xA

RAM_M68K_D6_STR:      equ RAM_M68K_D5_STR + RAM_M68K_D5_STR_SIZE
RAM_M68K_D6_STR_SIZE: equ 0xA

RAM_M68K_D7_STR:      equ RAM_M68K_D6_STR + RAM_M68K_D6_STR_SIZE
RAM_M68K_D7_STR_SIZE: equ 0xA

RAM_M68K_A0_STR:      equ RAM_M68K_D7_STR + RAM_M68K_D7_STR_SIZE
RAM_M68K_A0_STR_SIZE: equ 0xA

RAM_M68K_A1_STR:      equ RAM_M68K_A0_STR + RAM_M68K_A0_STR_SIZE
RAM_M68K_A1_STR_SIZE: equ 0xA

RAM_M68K_A2_STR:      equ RAM_M68K_A1_STR + RAM_M68K_A1_STR_SIZE
RAM_M68K_A2_STR_SIZE: equ 0xA

RAM_M68K_A3_STR:      equ RAM_M68K_A2_STR + RAM_M68K_A2_STR_SIZE
RAM_M68K_A3_STR_SIZE: equ 0xA

RAM_M68K_A4_STR:      equ RAM_M68K_A3_STR + RAM_M68K_A3_STR_SIZE
RAM_M68K_A4_STR_SIZE: equ 0xA

RAM_M68K_A5_STR:      equ RAM_M68K_A4_STR + RAM_M68K_A4_STR_SIZE
RAM_M68K_A5_STR_SIZE: equ 0xA

RAM_M68K_A6_STR:      equ RAM_M68K_A5_STR + RAM_M68K_A5_STR_SIZE
RAM_M68K_A6_STR_SIZE: equ 0xA

RAM_M68K_A7_STR:      equ RAM_M68K_A6_STR + RAM_M68K_A6_STR_SIZE
RAM_M68K_A7_STR_SIZE: equ 0xA

RAM_DEMO_MD_CORE_POS_X: equ RAM_M68K_A7_STR + RAM_M68K_A7_STR_SIZE
RAM_DEMO_MD_CORE_POS_X_SIZE: equ 0x4

RAM_DEMO_MD_CORE_POS_Y: equ RAM_DEMO_MD_CORE_POS_X + RAM_DEMO_MD_CORE_POS_X_SIZE
RAM_DEMO_MD_CORE_POS_Y_SIZE: equ 0x4
